/** SFU programs for the sign-up dropdown. Edit freely; keep "Other" and "Undeclared" at the end. */
export const PROGRAMS = [
  'Actuarial Science',
  'Anthropology',
  'Biological Sciences',
  'Biomedical Physiology and Kinesiology',
  'Business',
  'Chemistry',
  'Cognitive Science',
  'Communication',
  'Computing Science',
  'Contemporary Arts',
  'Criminology',
  'Data Science',
  'Earth Sciences',
  'Economics',
  'Education',
  'Engineering Science',
  'English',
  'Environmental Science',
  'Gender, Sexuality, and Women\'s Studies',
  'General Studies',
  'Geography',
  'Global Humanities',
  'Health Sciences',
  'History',
  'Indigenous Studies',
  'Interactive Arts and Technology',
  'International Studies',
  'Labour Studies',
  'Linguistics',
  'Mathematics',
  'Mechatronic Systems Engineering',
  'Molecular Biology and Biochemistry',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Publishing',
  'Resource and Environmental Management',
  'Sociology',
  'Software Systems',
  'Statistics',
  'Sustainable Energy Engineering',
  'Urban Studies',
  'World Languages and Literatures',
  'Undeclared',
  'Other',
] as const;
